import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%ALFRED_AGENT_HOOK_PORT%"=="" if defined ALFRED_AGENT_HOOK_ENDPOINT if exist "%ALFRED_AGENT_HOOK_ENDPOINT%" call "%ALFRED_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%ALFRED_AGENT_HOOK_TOKEN%"=="" if not "%ALFRED_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\alfred-dev\\agent-hooks" for /r "%APPDATA%\\alfred-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%ALFRED_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\alfred\\agent-hooks" for /r "%APPDATA%\\alfred\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%ALFRED_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set ALFRED_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%ALFRED_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__alfred_read_ancestor_var() {',
    '  __alfred_name="$1"',
    '  __alfred_pid="${PPID:-}"',
    '  while [ -n "$__alfred_pid" ] && [ "$__alfred_pid" != "0" ] && [ "$__alfred_pid" != "1" ]; do',
    '    __alfred_value=""',
    '    if [ -r "/proc/$__alfred_pid/environ" ]; then',
    '      __alfred_value=$(tr "\\000" "\\n" < "/proc/$__alfred_pid/environ" 2>/dev/null | sed -n "s/^${__alfred_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__alfred_value" ]; then',
    '      __alfred_value=$(ps eww -p "$__alfred_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__alfred_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__alfred_value" ]; then',
    '      printf "%s\\n" "$__alfred_value"',
    '      return 0',
    '    fi',
    '    __alfred_pid=$(ps -o ppid= -p "$__alfred_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__alfred_fill_from_ancestor() {',
    '  __alfred_name="$1"',
    '  case "$__alfred_name" in',
    '    ALFRED_AGENT_HOOK_ENDPOINT) [ -z "${ALFRED_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    ALFRED_AGENT_HOOK_PORT) [ -z "${ALFRED_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    ALFRED_AGENT_HOOK_TOKEN) [ -z "${ALFRED_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    ALFRED_AGENT_HOOK_ENV) [ -z "${ALFRED_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    ALFRED_AGENT_HOOK_VERSION) [ -z "${ALFRED_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    ALFRED_PANE_KEY) [ -z "${ALFRED_PANE_KEY:-}" ] || return 0 ;;',
    '    ALFRED_TAB_ID) [ -z "${ALFRED_TAB_ID:-}" ] || return 0 ;;',
    '    ALFRED_WORKTREE_ID) [ -z "${ALFRED_WORKTREE_ID:-}" ] || return 0 ;;',
    '    ALFRED_AGENT_LAUNCH_TOKEN) [ -z "${ALFRED_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __alfred_value=$(__alfred_read_ancestor_var "$__alfred_name") || return 0',
    '  [ -n "$__alfred_value" ] && export "$__alfred_name=$__alfred_value"',
    '}',
    '__alfred_endpoint_value() {',
    '  __alfred_endpoint_name="$1"',
    '  __alfred_endpoint_path="$2"',
    '  sed -n "s/^${__alfred_endpoint_name}=//p" "$__alfred_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__alfred_fill_from_endpoint_file() {',
    '  __alfred_endpoint_path="$1"',
    '  [ -r "$__alfred_endpoint_path" ] || return 0',
    '  __alfred_endpoint_port=$(__alfred_endpoint_value ALFRED_AGENT_HOOK_PORT "$__alfred_endpoint_path")',
    '  if [ -n "${ALFRED_AGENT_HOOK_PORT:-}" ] && [ -n "$__alfred_endpoint_port" ] && [ "$__alfred_endpoint_port" != "$ALFRED_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __alfred_endpoint_name in ALFRED_AGENT_HOOK_PORT ALFRED_AGENT_HOOK_TOKEN ALFRED_AGENT_HOOK_ENV ALFRED_AGENT_HOOK_VERSION; do',
    '    eval "__alfred_current=\\${$__alfred_endpoint_name:-}"',
    '    [ -z "$__alfred_current" ] || continue',
    '    __alfred_endpoint_value=$(__alfred_endpoint_value "$__alfred_endpoint_name" "$__alfred_endpoint_path")',
    '    [ -n "$__alfred_endpoint_value" ] && export "$__alfred_endpoint_name=$__alfred_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Alfred pane/hook metadata, so recover it before posting.',
    'for __alfred_name in ALFRED_AGENT_HOOK_ENDPOINT ALFRED_AGENT_HOOK_PORT ALFRED_AGENT_HOOK_TOKEN ALFRED_AGENT_HOOK_ENV ALFRED_AGENT_HOOK_VERSION ALFRED_PANE_KEY ALFRED_TAB_ID ALFRED_WORKTREE_ID ALFRED_AGENT_LAUNCH_TOKEN; do',
    '  __alfred_fill_from_ancestor "$__alfred_name"',
    'done',
    'if [ -n "$ALFRED_AGENT_HOOK_ENDPOINT" ] && [ -r "$ALFRED_AGENT_HOOK_ENDPOINT" ]; then',
    '  __alfred_fill_from_endpoint_file "$ALFRED_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# ALFRED_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$ALFRED_AGENT_HOOK_TOKEN" ] && [ -n "$ALFRED_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/alfred-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/alfred-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/alfred-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/alfred-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/alfred/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/alfred/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^ALFRED_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$ALFRED_AGENT_HOOK_PORT" ]; then',
    '      __alfred_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$ALFRED_AGENT_HOOK_PORT" ] || [ -z "$ALFRED_AGENT_HOOK_TOKEN" ] || [ -z "$ALFRED_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${ALFRED_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Alfred-Agent-Hook-Token: ${ALFRED_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${ALFRED_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${ALFRED_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${ALFRED_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${ALFRED_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${ALFRED_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${ALFRED_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
